#include "msc.h"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

/* Offline manual shown by `msc man`; README.md contains the full reference. */
static const char *MSC_MANUAL =
"NAME\n"
"    msc - parallel file transfer with standalone reliable UDP or TCP\n"
"\n"
"SYNOPSIS\n"
"    msc [-h] [-l localmachine,...] -r remote[,...]\n"
"        [-i inputfile] [-o outputfile] | [-c remote-command]\n"
"        [-u username] [-B remote-msc] [-n flows] [-p port] [-s bytes]\n"
"        [-t length] [-a source-offset] [-b destination-offset] [-R] [-T|-U]\n"
"        [-I data-host] [--env NAME] [--force] [--gso|--no-gso] [--gro|--no-gro]\n"
"        [--stats] [--checksum=true|false] [--port-tries N]\n"
"        [--dest-stripe-count N]\n"
"        [--udp-data-ports K] [--udp-port-base PORT] [--udp-port-span S]\n"
"        [--udp-ports LIST]\n"
"        [--resume] [--checkpoint PATH] [--keep-checkpoint]\n"
"        [--retries N] [--retry-delay DURATION]\n"
"        [--progress=auto|always|never] [--progress-interval DURATION]\n"
"        [--stall-timeout DURATION] [--reconnect-interval DURATION]\n"
"\n"
"DESCRIPTION\n"
"    MSC launches a peer through SSH and transfers a file, a directory tree,\n"
"    or a stdin/command stream. MSC's own reliable-UDP transport is the\n"
"    default; -T selects TCP, and -U spells the default out. Because the UDP\n"
"    engine moves a file to a file, a transfer that reads stdin or writes to a\n"
"    -c program runs on TCP; combining -U with either is an error.\n"
"\n"
"    The UDP sender uses parallel flows with sliding windows,\n"
"    cumulative ACK and SACK recovery, adaptive retransmission,\n"
"    congestion control, pacing, and path-MTU discovery. UDP GSO and GRO are\n"
"    used when available and fall back gracefully when unavailable.\n"
"\n"
"    The receiving peer must run the same MSC protocol version. Use -B with\n"
"    an absolute path when msc is not on the remote non-interactive PATH.\n"
"\n"
"OPTIONS\n"
"    -l hosts             Source-side machine list; count must match -r.\n"
"    -r hosts             Destination-side machine list.\n"
"    -i path              Input file or source directory.\n"
"    -o path              Output file or destination directory.\n"
"    -c command           Feed transferred stdin to a remote command.\n"
"    -B path              Remote MSC executable (default: msc from PATH).\n"
"    -n N                 Parallel TCP streams or UDP flows.\n"
"    -s bytes             TCP chunk size or explicit UDP payload size.\n"
"    -t bytes             Transfer-length slice.\n"
"    -a bytes             Source offset.\n"
"    -b bytes             Destination offset.\n"
"    -R                   Recursively transfer a directory.\n"
"    -T                   Use TCP instead of the default reliable UDP.\n"
"    -U                   Use reliable UDP (the default, named explicitly).\n"
"    -I host              Address used by the UDP sender.\n"
"    --env NAME           UDP only. Transport preset for the path being crossed.\n"
"                         Name it whenever you know the path: the defaults were\n"
"                         tuned on a local fabric and are slow over latency, and\n"
"                         auto can only guess from RTT once data is flowing.\n"
"                           lan                        same fabric or rack, <5ms\n"
"                           wan/fiber/fiber-shared     another city, 5-120ms\n"
"                           wan-long/fiber-long/       another continent,\n"
"                             longhaul                 120-450ms\n"
"                           geo/satellite              satellite hop, 450ms+\n"
"                           auto (default)             picked from measured RTT\n"
"                         Sets MSC_UDP_PROFILE, which an explicit environment\n"
"                         value still overrides. MSC_UDP_STATS=1 reports the\n"
"                         preset in force and the RTT it was chosen from.\n"
"    --force              Atomically replace an existing UDP destination.\n"
"    --gso, --no-gso      Enable or disable UDP_SEGMENT (default enabled).\n"
"    --gro, --no-gro      Enable or disable UDP_GRO (default enabled).\n"
"    --stats              Print per-flow UDP transport statistics.\n"
"    --checksum=BOOL      UDP checksum/publication validation (default false).\n"
"    --port-tries N       Control ports to try starting at -p.\n"
"    --dest-stripe-count N\n"
"                         Lustre: create the DESTINATION file striped over N\n"
"                         OSTs, or every OST with -1. Without it the\n"
"                         destination keeps matching the source's stripe\n"
"                         count, which is still the default. This controls\n"
"                         destination creation only -- the source layout still\n"
"                         drives how the transport maps units to flows, so\n"
"                         asking for a width that differs from the source's\n"
"                         gives up the receiver's OST affinity and can change\n"
"                         write throughput. Applies to a single destination\n"
"                         file: -R and -c are refused. A layout that cannot be\n"
"                         applied is an error, never a silent fallback to the\n"
"                         directory default. Asking for more OSTs than the\n"
"                         filesystem has is clamped to all of them, as in\n"
"                         lfs setstripe -c N.\n"
"    --udp-data-ports K   UDP only. Carry the -n UDP flows on K data sockets\n"
"                         (flow f uses socket f mod K). Fewer ports for a\n"
"                         firewall to open, at the cost of throughput on a\n"
"                         fast fabric: flows sharing a socket are fed by one\n"
"                         demultiplexing thread. K is clamped to -n.\n"
"                         Default: min(-n, 8).\n"
"    --udp-port-base PORT UDP only. First port of the window msc scans for its\n"
"                         K data ports: it tries PORT, PORT+1, ... and keeps\n"
"                         the first K that are free, so concurrent transfers\n"
"                         (yours or another user's) land on disjoint ports\n"
"                         without coordinating. Default: 17400.\n"
"    --udp-port-span S    UDP only. Width of that window, i.e. how many ports\n"
"                         may be tried. Default 4*K, which is roughly how\n"
"                         many concurrent transfers of this shape fit before\n"
"                         one must fail. S=0 disables scanning: msc then\n"
"                         binds the exact block PORT..PORT+K-1 and refuses to\n"
"                         start if any of them is busy.\n"
"    --udp-ports LIST     UDP only. Use exactly these ports, in this order:\n"
"                         a comma list of ports and lo-hi ranges, e.g.\n"
"                         20000,20004,20100-20103. K comes from the list. If\n"
"                         any listed port is in use msc names it and refuses\n"
"                         to start; it never quietly moves off the list.\n"
"                         The ports actually in use are printed on stderr at\n"
"                         the start of every transfer, whichever form is used.\n"
"    --checkpoint PATH    Create durable receiver checkpoints.\n"
"    --resume             Continue from a valid checkpoint.\n"
"    --keep-checkpoint    Retain a completed checkpoint.\n"
"    --stall-timeout D    Stop after D without network progress; 0 disables.\n"
"\n"
"UDP PUBLICATION AND RESUME\n"
"    A single-file UDP receive is written to .msc-udptmp.<pid> and published\n"
"    atomically after successful delivery and optional checksum validation.\n"
"    Recursive UDP destinations are updated in place and may remain as partial\n"
"    trees after interruption. Their regular files form one logical byte space\n"
"    in manifest order; a durable range may cross file boundaries. Files and\n"
"    manifest directory entries are synced before a range is checkpointed.\n"
"    Durable ranges are independent of UDP packet geometry, so resume may use\n"
"    a different path-MTU ceiling and payload size. Resume rejects changed\n"
"    source or destination identity. Before reusing bytes, both peers compare\n"
"    SHA-256 over every claimed source/destination range; same-size partial\n"
"    edits fail with exit 7. A complete tree checkpoint survives interrupted\n"
"    final metadata and lets the next run skip file data. Checkpoint v2 binds\n"
"    offsets and transfer length and rejects older checkpoints. Checkpointed\n"
"    UDP slices are not supported.\n"
"\n"
"UDP ENVIRONMENT\n"
"    UDP controls use the MSC_UDP_* namespace. Documented variables include\n"
"    MSC_UDP_CC, MSC_UDP_PACE, MSC_UDP_PACE_GAIN, MSC_UDP_PACE_BURST,\n"
"    MSC_UDP_ACK_EVERY, MSC_UDP_DUPACK_THRESH, MSC_UDP_REORDER_WAIT_MS,\n"
"    MSC_UDP_RWND, MSC_UDP_PMTUD, MSC_UDP_PMTUD_CAP, MSC_UDP_GSO,\n"
"    MSC_UDP_GRO, MSC_UDP_SOCK_BUFFER, MSC_UDP_CTL, MSC_UDP_STATS, and\n"
"    MSC_UDP_STALL_TIMEOUT_MS. MSC_UDP_PROFILE selects a path preset (the\n"
"    --env flag sets it); auto chooses among lan, wan, wan-long, and geo from\n"
"    the handshake RTT, then corrects that choice once a real data-path RTT\n"
"    sample arrives. wan-long covers long-haul and intercontinental fiber\n"
"    (>= 120 ms), where the bandwidth-delay product is large enough that the\n"
"    startup ramp, not the steady state, decides the transfer; geo is the\n"
"    satellite hop (>= 450 ms). MSC_UDP_WAN_RTT_MS, MSC_UDP_WAN_LONG_RTT_MS,\n"
"    and MSC_UDP_GEO_RTT_MS move the auto thresholds, and\n"
"    MSC_UDP_STARTUP_QUEUE_MULT overrides the preset's delay-based startup\n"
"    exit (0 disables it). Only documented names are forwarded through the SSH launch\n"
"    command, and their values are shell-quoted.\n"
"\n"
"EXIT STATUS\n"
"    0 success; 2 CLI; 3 source; 4 destination; 5 authentication/launch;\n"
"    6 network/transport; 7 integrity; 8 protocol incompatibility;\n"
"    70 internal; 130 SIGINT; 143 SIGTERM.\n"
"\n"
"FILES\n"
"    src/udp_transport.c   CLI, manifest, checkpoint, and publication bridge\n"
"    src/udp_session.[ch]  reliable data protocol and session API\n"
"    src/udp_control.c     reliable control channel and receive demultiplexer\n"
"    src/udp_io.c          private I/O, checksum, and optional Lustre helpers\n"
"    src/udp_stats.[ch]    transport statistics\n"
"\n"
"SEE ALSO\n"
"    msc -h                short option summary\n"
"    msc/README.md         complete build, operation, and test reference\n"
;

void print_manual(void)
{
   FILE *out = stdout;
   FILE *pager = NULL;
   const char *pager_cmd;

   if (isatty(fileno(stdout)))
   {
      pager_cmd = getenv("PAGER");
      if (pager_cmd == NULL || *pager_cmd == '\0')
         pager_cmd = "less -R";
      pager = popen(pager_cmd, "w");
      if (pager != NULL)
         out = pager;
   }

   fputs(MSC_MANUAL, out);
   if (pager != NULL)
      pclose(pager);
}
